#ifndef __PINOUT_H__
#define __PINOUT_H__

#define AHEAD_SENSOR A5
#define BEHIND_SENSOR A4
#define RIGHT_ROTARY_ENCODER A1
#define LEFT_ROTARY_ENCODER A0

#define RIGHT_MOTOR_PWM 10
#define LEFT_MOTOR_PWM 9

#define AHEAD_RIGHT_RELAY 7
#define AHEAD_LEFT_RELAY 5
#define BEHIND_RIGHT_RELAY 8
#define BEHIND_LEFT_RELAY 6

#define JUMPER 4

#endif
